name: Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ latest, stable ]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Docker info
        run: docker info
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Setup bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.1
        with:
          support-path: "${{ github.workspace }}/tests/bats-support"
          assert-path: "${{ github.workspace }}/tests/bats-assert"
          detik-path: "${{ github.workspace }}/tests/bats-detik"
          file-path: "${{ github.workspace }}/tests/bats-file"
      -
        name: "Test ddev ${{ matrix.version }} image"
        shell: 'script -q -e -c "bash {0}"'
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: |
          sudo snap install yq
          ./build.sh -v ${{ matrix.version }} -l
          DDEV_VERSION=${{ matrix.version }} bash bats tests
